import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

// Cache version - update this to force cache refresh
const CACHE_VERSION = 'v2';

// Precache files generated by Next.js build
precacheAndRoute(self.__WB_MANIFEST || []);

// Clean up outdated caches
cleanupOutdatedCaches();

// Cache the main app shell and prayer pages with offline-first approach
registerRoute(
	({ request, url }) => {
		return (
			request.mode === 'navigate' &&
			(url.pathname === '/' ||
				url.pathname === '/index' ||
				url.pathname === '/offline' ||
				// Match prayer page routes (any path that doesn't start with /api/ or special paths)
				(!url.pathname.startsWith('/api/') &&
					!url.pathname.startsWith('/_next/') &&
					!url.pathname.startsWith('/static/') &&
					!url.pathname.endsWith('.js') &&
					!url.pathname.endsWith('.css') &&
					!url.pathname.endsWith('.json') &&
					!url.pathname.endsWith('.ico')))
		);
	},
	new CacheFirst({
		cacheName: `pages-cache-${CACHE_VERSION}`,
		plugins: [
			new CacheableResponsePlugin({
				statuses: [0, 200],
			}),
			new ExpirationPlugin({
				maxEntries: 100,
				maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
			}),
		],
	})
);

// Cache API calls with offline-first approach
registerRoute(
	({ url }) => url.pathname.startsWith('/api/prayers'),
	new CacheFirst({
		cacheName: 'prayers-api-cache',
		plugins: [
			new CacheableResponsePlugin({
				statuses: [0, 200],
			}),
			new ExpirationPlugin({
				maxEntries: 100,
				maxAgeSeconds: 60 * 60 * 24 * 90, // 90 days
			}),
		],
	})
);

// Cache individual prayer API calls
registerRoute(
	({ url }) => url.pathname.startsWith('/api/prayer/'),
	new CacheFirst({
		cacheName: 'prayer-details-cache',
		plugins: [
			new CacheableResponsePlugin({
				statuses: [0, 200],
			}),
			new ExpirationPlugin({
				maxEntries: 500,
				maxAgeSeconds: 60 * 60 * 24 * 90, // 90 days
			}),
		],
	})
);

// Cache static assets (JS, CSS, images) with long-term caching
registerRoute(
	({ request }) =>
		request.destination === 'script' ||
		request.destination === 'style' ||
		request.destination === 'image' ||
		request.destination === 'font',
	new CacheFirst({
		cacheName: 'static-resources',
		plugins: [
			new CacheableResponsePlugin({
				statuses: [0, 200],
			}),
			new ExpirationPlugin({
				maxEntries: 200,
				maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
			}),
		],
	})
);

// Cache all _next static files aggressively
registerRoute(
	({ url }) => url.pathname.startsWith('/_next/static/'),
	new CacheFirst({
		cacheName: 'next-static-cache',
		plugins: [
			new CacheableResponsePlugin({
				statuses: [0, 200],
			}),
			new ExpirationPlugin({
				maxEntries: 300,
				maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
			}),
		],
	})
);

// Handle offline navigation - serve cached page or offline page
registerRoute(
	new NavigationRoute(
		new CacheFirst({
			cacheName: `navigation-cache-${CACHE_VERSION}`,
			plugins: [
				new CacheableResponsePlugin({
					statuses: [0, 200],
				}),
				new ExpirationPlugin({
					maxEntries: 50,
					maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
				}),
			],
		})
	)
);

// Install event - cache essential resources immediately
self.addEventListener('install', (event) => {
	console.log('Service Worker installing...');

	// Cache essential pages immediately and aggressively
	event.waitUntil(
		Promise.all([
			// Cache in essential cache - including all main pages
			caches.open(`essential-cache-${CACHE_VERSION}`).then((cache) => {
				return cache
					.addAll([
						'/',
						'/offline', 
						'/manifest.json',
						'/_next/static/css/c17eec73476ddc06.css', // Main CSS file
						'/_next/static/chunks/main-e9932c24240317b9.js', // Main JS
						'/_next/static/chunks/framework-768692517470e708.js', // React framework
						'/_next/static/chunks/webpack-5e931bb610e47be1.js', // Webpack runtime
					])
					.catch((error) => {
						console.warn('Failed to cache essential resources:', error);
					});
			}),
			// Also cache in pages cache for better lookup
			caches.open(`pages-cache-${CACHE_VERSION}`).then((cache) => {
				return cache.addAll(['/', '/offline']).catch((error) => {
					console.warn('Failed to cache pages:', error);
				});
			}),
		])
	);

	// Force immediate activation
	self.skipWaiting();
});

// Activate event - take control immediately and clean old caches
self.addEventListener('activate', (event) => {
	console.log('Service Worker activating...');
	event.waitUntil(
		Promise.all([
			self.clients.claim(),
			// Clean up old caches
			caches.keys().then((cacheNames) => {
				return Promise.all(
					cacheNames.map((cacheName) => {
						// Delete old versions of our caches
						if (
							cacheName.includes('pages-cache') &&
							!cacheName.includes(CACHE_VERSION)
						) {
							console.log('Deleting old cache:', cacheName);
							return caches.delete(cacheName);
						}
						if (
							cacheName.includes('essential-cache') &&
							!cacheName.includes(CACHE_VERSION)
						) {
							console.log('Deleting old cache:', cacheName);
							return caches.delete(cacheName);
						}
						return null;
					})
				);
			}),
		])
	);
});

// Handle fetch events for better offline support
self.addEventListener('fetch', (event) => {
	// Handle navigation requests specially for offline-first behavior
	if (event.request.mode === 'navigate') {
		event.respondWith(
			// Try network first with shorter timeout for better offline experience
			Promise.race([
				fetch(event.request),
				new Promise((_, reject) =>
					setTimeout(() => reject(new Error('Network timeout')), 800)
				),
			])
				.then((response) => {
					// If online and successful, cache the response for future offline use
					if (response.ok) {
						const responseClone = response.clone();
						Promise.all([
							caches
								.open(`pages-cache-${CACHE_VERSION}`)
								.then((cache) => {
									cache.put(
										event.request,
										responseClone.clone()
									);
								}),
							caches
								.open(`essential-cache-${CACHE_VERSION}`)
								.then((cache) => {
									if (
										event.request.url.endsWith('/') ||
										event.request.url.includes(
											'localhost:3000'
										) ||
										event.request.url.includes(location.host)
									) {
										cache.put(
											event.request,
											responseClone.clone()
										);
									}
								}),
						]);
					}
					return response;
				})
				.catch(async () => {
					console.log(
						'Network failed, serving from cache for:',
						event.request.url
					);

					// Aggressive offline fallback strategy for navigation
					// 1. Try exact URL match across all caches
					let cachedResponse = await caches.match(event.request, {
						ignoreSearch: true,
						ignoreVary: true
					});
					if (cachedResponse) {
						console.log('Found exact navigation match in cache');
						return cachedResponse;
					}

					// 2. Try pathname variations
					const url = new URL(event.request.url);
					const pathname = url.pathname;
					
					const cacheNames = [
						`pages-cache-${CACHE_VERSION}`,
						`essential-cache-${CACHE_VERSION}`,
						'pages-cache', // fallback to old cache
						'essential-cache-v1' // fallback to v1
					];
					
					for (const cacheName of cacheNames) {
						try {
							const cache = await caches.open(cacheName);
							
							// Try exact pathname
							cachedResponse = await cache.match(pathname);
							if (cachedResponse) {
								console.log(`Found pathname match in ${cacheName}`);
								return cachedResponse;
							}
							
							// Try with trailing slash
							if (!pathname.endsWith('/')) {
								cachedResponse = await cache.match(pathname + '/');
								if (cachedResponse) {
									console.log(`Found pathname with slash in ${cacheName}`);
									return cachedResponse;
								}
							}
							
							// Try without trailing slash
							if (pathname.endsWith('/') && pathname.length > 1) {
								cachedResponse = await cache.match(pathname.slice(0, -1));
								if (cachedResponse) {
									console.log(`Found pathname without slash in ${cacheName}`);
									return cachedResponse;
								}
							}
						} catch (cacheError) {
							console.warn(`Error accessing cache ${cacheName}:`, cacheError);
						}
					}

					// 3. Try home page from any cache as fallback
					for (const cacheName of cacheNames) {
						try {
							const cache = await caches.open(cacheName);
							cachedResponse = await cache.match('/');
							if (cachedResponse) {
								console.log(`Serving home page from ${cacheName} as fallback`);
								return cachedResponse;
							}
						} catch (cacheError) {
							console.warn(`Error accessing home page in cache ${cacheName}:`, cacheError);
						}
					}

					// 4. Last resort - enhanced inline offline response with proper styling
					console.log('Serving enhanced inline offline response');
					return new Response(
						`<!DOCTYPE html>
<html lang="en" data-theme="light">
  <head>
    <title>Offline - Prayer App</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#317EFB">
    <style>
      :root {
        --primary: #317EFB;
        --primary-hover: #2563eb;
        --bg: #f8f9fa;
        --card-bg: white;
        --text: #212529;
        --text-muted: #666;
        --border: #e9ecef;
        --shadow: rgba(0,0,0,0.1);
      }
      
      [data-theme="dark"] {
        --bg: #121212;
        --card-bg: #1e1e1e;
        --text: #ffffff;
        --text-muted: #aaa;
        --border: #333;
        --shadow: rgba(0,0,0,0.3);
      }
      
      * { margin: 0; padding: 0; box-sizing: border-box; }
      
      body { 
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
        margin: 0; padding: 20px; text-align: center; 
        background: var(--bg); min-height: 100vh; color: var(--text);
        display: flex; align-items: center; justify-content: center;
      }
      
      .offline-container { 
        background: var(--card-bg); padding: 40px; border-radius: 12px; 
        box-shadow: 0 4px 20px var(--shadow); max-width: 400px; 
        border: 1px solid var(--border);
      }
      
      .offline { color: var(--text-muted); }
      
      .back-btn { 
        margin: 10px 5px; padding: 12px 20px; 
        background: var(--primary); color: white; border: none; 
        border-radius: 8px; cursor: pointer; font-size: 14px;
        text-decoration: none; display: inline-block;
        transition: background-color 0.2s ease;
      }
      
      .back-btn:hover { background: var(--primary-hover); }
      .retry-btn { background: #6c757d; }
      .retry-btn:hover { background: #5a6268; }
      
      h1 { color: var(--primary); margin-bottom: 20px; font-size: 2em; }
      p { margin-bottom: 16px; line-height: 1.5; }
      strong { color: var(--text); }
      
      .status { 
        background: #ffeaa7; color: #2d3436; padding: 12px; 
        border-radius: 6px; margin: 16px 0; font-weight: 500;
      }
    </style>
  </head>
  <body>
    <div class="offline-container">
      <div class="offline">
        <h1>📱 Prayer App</h1>
        <div class="status">You're currently offline</div>
        <p><strong>This content isn't available offline yet.</strong></p>
        <p>To access prayers offline, please:</p>
        <ol style="text-align: left; margin: 16px 0; padding-left: 20px;">
          <li>Connect to the internet</li>
          <li>Use the download button (💾) to cache content</li>
          <li>Then you can use the app offline</li>
        </ol>
        <button class="back-btn" onclick="window.history.back()">← Go Back</button>
        <button class="back-btn" onclick="window.location.href='/'">🏠 Home</button>
        <br><br>
        <button class="back-btn retry-btn" onclick="window.location.reload()">🔄 Retry</button>
      </div>
    </div>
  </body>
</html>`,
						{
							headers: { 'Content-Type': 'text/html' },
							status: 200,
						}
					);
				})
		);
		return;
	}
	
	// Handle API requests with aggressive offline-first caching
	if (event.request.url.includes('/api/')) {
		event.respondWith(
			caches.match(event.request).then(async (cachedResponse) => {
				if (cachedResponse) {
					console.log('Serving API from cache:', event.request.url);
					// Serve from cache immediately, update in background if online
					if (navigator.onLine) {
						fetch(event.request).then(response => {
							if (response && response.ok) {
								caches.open('prayers-api-cache').then(cache => {
									cache.put(event.request, response.clone());
								});
							}
						}).catch(() => {}); // Silent background update
					}
					return cachedResponse;
				}
				
				// If not in cache, try network
				return fetch(event.request).then(response => {
					if (response && response.ok) {
						const responseClone = response.clone();
						caches.open('prayers-api-cache').then(cache => {
							cache.put(event.request, responseClone);
						});
					}
					return response;
				}).catch(() => {
					// Network failed and no cache available
					console.log('API request failed offline:', event.request.url);
					return new Response('{"error": "Content not available offline"}', {
						status: 503,
						headers: { 'Content-Type': 'application/json' }
					});
				});
			})
		);
		return;
	}
	
	// Handle static resources aggressively for offline functionality
	if (
		event.request.destination === 'script' ||
		event.request.destination === 'style' ||
		event.request.destination === 'image' ||
		event.request.destination === 'font' ||
		event.request.url.includes('/_next/static/') ||
		event.request.url.includes('/static/')
	) {
		event.respondWith(
			caches.match(event.request).then(async (cachedResponse) => {
				if (cachedResponse) {
					console.log('Serving static asset from cache:', event.request.url);
					return cachedResponse;
				}
				
				// Try to fetch and cache for future offline use
				return fetch(event.request).then(response => {
					if (response && response.ok) {
						const responseClone = response.clone();
						caches.open('static-resources').then(cache => {
							cache.put(event.request, responseClone);
						});
					}
					return response;
				}).catch(() => {
					console.log('Static asset failed offline:', event.request.url);
					return new Response('', { status: 503 });
				});
			})
		);
		return;
	}
});

// Listen for messages from the main thread
self.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') {
		self.skipWaiting();
	}
});